# Generated by Django 4.1.1 on 2022-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habitacion', models.IntegerField(null=True, verbose_name='Habitación')),
                ('cama', models.IntegerField(null=True, verbose_name='Cama')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('diagnostico', models.CharField(max_length=100, verbose_name='Diagnóstico')),
                ('observaciones', models.CharField(max_length=150, verbose_name='Observaciones')),
                ('desayuno', models.TextField(null=True, verbose_name='Desayuno')),
                ('colacion_maniana', models.TextField(null=True, verbose_name='Colación M')),
                ('almuerzo', models.TextField(null=True, verbose_name='Almuerzo')),
                ('merienda', models.TextField(null=True, verbose_name='Merienda')),
                ('colacion_tarde', models.TextField(null=True, verbose_name='Colación T')),
                ('cena', models.TextField(null=True, verbose_name='Cena')),
                ('comida_familiar', models.TextField(null=True, verbose_name='Comida Familiar')),
                ('comentarios', models.CharField(max_length=150, verbose_name='Comentarios')),
            ],
        ),
    ]
