# Generated by Django 4.1.1 on 2022-09-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='almuerzo',
            field=models.CharField(max_length=30, null=True, verbose_name='Almuerzo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cena',
            field=models.CharField(max_length=30, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='colacion_maniana',
            field=models.CharField(max_length=30, null=True, verbose_name='Colación M'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='colacion_tarde',
            field=models.CharField(max_length=30, null=True, verbose_name='Colación T'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comentarios',
            field=models.TextField(verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comida_familiar',
            field=models.CharField(max_length=30, null=True, verbose_name='Comida Familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='desayuno',
            field=models.CharField(max_length=30, null=True, verbose_name='Desayuno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.CharField(max_length=30, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='merienda',
            field=models.CharField(max_length=30, null=True, verbose_name='Merienda'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='observaciones',
            field=models.TextField(verbose_name='Observaciones'),
        ),
    ]
