# Generated by Django 4.1.1 on 2022-09-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip5', '0002_alter_paciente_almuerzo_alter_paciente_cena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='postre',
            field=models.CharField(max_length=30, null=True, verbose_name='Postre'),
        ),
    ]
