# Generated by Django 4.1.1 on 2022-09-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip5', '0003_paciente_postre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='almuerzo',
            field=models.CharField(max_length=50, null=True, verbose_name='Almuerzo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cena',
            field=models.CharField(max_length=50, null=True, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='colacion_maniana',
            field=models.CharField(max_length=50, null=True, verbose_name='Colación M'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='colacion_tarde',
            field=models.CharField(max_length=50, null=True, verbose_name='Colación T'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='desayuno',
            field=models.CharField(max_length=50, null=True, verbose_name='Desayuno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='merienda',
            field=models.CharField(max_length=50, null=True, verbose_name='Merienda'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
